export const items = [
    {
      id: 1,
      url: "/assets/img/pw_img_14.webp",
      title: "Introducing pixel wheels",
      description: "Innovative marking platform",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 2,
      video: true,
      url: "https://player.vimeo.com/video/917046197?controls=0&autoplay=1&loop=1&muted=1&title=0&autopause=0&background=1",
      title: "Advertisement on wheels",
      description: "Adding more colours to the nature",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 3,
      url: "/assets/img/pw_img_3.webp",
      title: "Street Academics promotion",
      description: "We undertake promotion and digital ads",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 4,
      url: "/assets/img/pw_img_4.webp",
      title: "Street Academics promotion II",
      description: "We undertake promotion and digital ads",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 5,
      video: true,
      url: "https://player.vimeo.com/video/919497295?controls=0&autoplay=1&loop=1&muted=1&title=0&autopause=0&background=1",
      title: "Pixel wheels 360",
      description: "India's first 3 sided mobile advertising platform",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 6,
      url: "/assets/img/pw_img_7.webp",
      title: "Lorem ipsum",
      description: "Lorem ipsum dolor",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 7,
      url: "/assets/img/pw_img_8.webp",
      // url: "https://images.unsplash.com/photo-1662541109467-a80473ab73e4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80",
      title: "Lorem ipsum",
      description: "Lorem ipsum dolor",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 8,
      url: "/assets/img/pw_img_9.webp",
      title: "Lorem ipsum",
      description: "Lorem ipsum dolor",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 9,
      url: "/assets/img/pw_img_10.webp",
      title: "Lorem ipsum",
      description: "Lorem ipsum dolor",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 10,
      url: "/assets/img/pw_img_11.webp",
      title: "Lorem ipsum",
      description: "Lorem ipsum dolor",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 11,
      url: "/assets/img/pw_img_12.webp",
      title: "Lorem ipsum",
      description: "Lorem ipsum dolor",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 12,
      url: "/assets/img/pw_img_13.webp",
      title: "Lorem ipsum",
      description: "Lorem ipsum dolor",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
  ];