export const items = [
    {
      id: 1,
      url: "/assets/img/pw_img_1.webp",
      title: "Introducing pixel wheels",
      description: "Innovative marking platform",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 2,
      video: true,
      url: "https://player.vimeo.com/video/917046197?controls=0&autoplay=1&loop=1&muted=1&title=0&autopause=0&background=1",
      title: "Advertisement on wheels",
      description: "Adding more colours to the nature",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 3,
      url: "/assets/img/pw_img_3.webp",
      title: "Street Academics promotion",
      description: "We undertake promotion and digital ads",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 4,
      url: "/assets/img/pw_img_4.webp",
      title: "Street Academics promotion II",
      description: "We undertake promotion and digital ads",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 5,
      video: true,
      url: "https://player.vimeo.com/video/919497295?controls=0&autoplay=1&loop=1&muted=1&title=0&autopause=0&background=1",
      title: "Pixel wheels 360",
      description: "India's first 3 sided mobile advertising platform",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 6,
      url: "https://images.unsplash.com/photo-1507629221898-576a56b530bb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=688&q=80",
      title: "Lorem ipsum",
      description: "Lorem ipsum dolor",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 7,
      url: "/assets/img/pw_img_7.png",
      // url: "https://images.unsplash.com/photo-1662541109467-a80473ab73e4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80",
      title: "Lorem ipsum",
      description: "Lorem ipsum dolor",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 8,
      url: "https://images.unsplash.com/photo-1662544954782-4c137c9b34a7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=735&q=80",
      title: "Lorem ipsum",
      description: "Lorem ipsum dolor",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 9,
      url: "https://images.unsplash.com/photo-1659536009108-ebe9053222d4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80",
      title: "Lorem ipsum",
      description: "Lorem ipsum dolor",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 10,
      url: "https://images.unsplash.com/photo-1662532577856-e8ee8b138a8b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1456&q=80",
      title: "Lorem ipsum",
      description: "Lorem ipsum dolor",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 11,
      url: "https://images.unsplash.com/photo-1662436267874-4ab1145ade4a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1886&q=80",
      title: "Lorem ipsum",
      description: "Lorem ipsum dolor",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
    {
      id: 12,
      url: "https://images.unsplash.com/photo-1662514282655-438b87b04995?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
      title: "Lorem ipsum",
      description: "Lorem ipsum dolor",
      tags: ["Mountains", "Aesthetic", "Pretty", "Scenic", "Rugged"],
    },
  ];